spring:
  profiles:
    active: local

server:
  port: 8080

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

logging:
  level:
    root: info
---

spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

---

spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
